In [1]:
a = 10        # int
b = 3.14      # float
c = True      # bool
d = "Hello"   # string

print(type(a), type(b), type(c), type(d))


<class 'int'> <class 'float'> <class 'bool'> <class 'str'>


In [ ]:
# Numpy from beginning to end and beyond

import numpy as np
print(np.__version__)

1.23.5


In [ ]:
#creating numpy array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr1=arr*2
print(arr1)

[ 2  4  6  8 10]


In [4]:
#creating multi-dimensional array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)

[[1 2 3]
 [4 5 6]]
2


In [14]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1)
print(arr1.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [6]:
#Array Shape
print(arr1.shape)

(2, 2, 3)


In [7]:
##  Creating Arrays in different ways using numpy
# 1. Using arange() function
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [10]:
# using zeros() function
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
print(arr.ndim)

2


In [12]:
print(arr.shape)

(3, 4)


In [13]:
#using ones() function
arr=np.ones((2,3,4))
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
(2, 3, 4)


In [15]:
# using linspace() function
arr=np.linspace(1,10,5)
print(arr)
print(arr.ndim)
print(arr.shape)

[ 1.    3.25  5.5   7.75 10.  ]
1
(5,)


In [18]:
#using logspace() function
arr=np.logspace(1,2,5)
print(arr)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [21]:
#using empty() function
arr=np.empty((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
#using random() function and rand function
arr=np.random.rand(3,4)
print(arr)

[[0.67424574 0.87324505 0.35427738 0.21551219]
 [0.30088736 0.94082693 0.5218445  0.759104  ]
 [0.34281706 0.15604956 0.32797674 0.41693401]]


In [ ]:
arr=np.random.randn(3,4)
arr1=np.random.randint(1,10,(3,4))
print(arr)
print(arr1)