In [1]:
a = 10        # int
b = 3.14      # float
c = True      # bool
d = "Hello"   # string

print(type(a), type(b), type(c), type(d))


<class 'int'> <class 'float'> <class 'bool'> <class 'str'>


In [3]:
# Numpy from beginning to end and beyond

import numpy as np
print(np.__version__)

1.23.5


In [ ]:
#creating numpy array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr1=arr*2
print(arr1)

[ 2  4  6  8 10]


In [4]:
#creating multi-dimensional array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)

[[1 2 3]
 [4 5 6]]
2


In [14]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1)
print(arr1.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [6]:
#Array Shape
print(arr1.shape)

(2, 2, 3)


In [7]:
##  Creating Arrays in different ways using numpy
# 1. Using arange() function
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [10]:
# using zeros() function
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
print(arr.ndim)

2


In [12]:
print(arr.shape)

(3, 4)


In [13]:
#using ones() function
arr=np.ones((2,3,4))
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
(2, 3, 4)


In [15]:
# using linspace() function
arr=np.linspace(1,10,5)
print(arr)
print(arr.ndim)
print(arr.shape)

[ 1.    3.25  5.5   7.75 10.  ]
1
(5,)


In [18]:
#using logspace() function
arr=np.logspace(1,2,5)
print(arr)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [21]:
#using empty() function
arr=np.empty((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
#using random() function and rand function
arr=np.random.rand(3,4)
print(arr)

[[0.67424574 0.87324505 0.35427738 0.21551219]
 [0.30088736 0.94082693 0.5218445  0.759104  ]
 [0.34281706 0.15604956 0.32797674 0.41693401]]


In [24]:
arr=np.random.randn(3,4)
arr1=np.random.randint(1,10,(3,4))
print(arr)
print(arr1)

[[-0.96393793 -0.43602397  0.70373594 -0.23403193]
 [-0.32814561  1.37708338 -0.46402819 -2.41772828]
 [-1.3264655   0.95478968  0.0076256   0.28814936]]
[[4 9 5 5]
 [9 9 5 8]
 [3 9 7 3]]


In [25]:
#using full() function
arr=np.full((3,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#numpy Data types
arr=np.array([1,2,3,4])
print(arr.dtype)
arr=np.array([1.1,2.2,3.3])
print(arr.dtype)



int32
float64
|S1


In [27]:
#type casting
arr=np.array([1,2,3,4])
print(arr.dtype)
arr=arr.astype('float')
print(arr)
print(arr.dtype)

int32
[1. 2. 3. 4.]
float64


In [30]:
# array reshaping
arr=np.arange(1,11)
print(arr)
print(arr.ndim)
print(arr.shape)
arr=arr.reshape(2,5)
print(arr)
print(arr.ndim)
print(arr.shape)
arr=arr.reshape(5,2)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [35]:
#use of revel() function
arr=np.array([[1,2,3],[4,5,6]])
revel=arr.ravel()
print(revel)
print(arr)
revel[0]=10
print(arr)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[10  2  3]
 [ 4  5  6]]


In [37]:
#arethmetic operations on array
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**arr2)
print(arr1//arr2)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[0 0 0 0]


In [44]:
#Indexing and slicing
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
print(arr[0:5])
print(arr[3:7])


1
[1 2 3 4 5]
[4 5 6 7]


In [45]:
print(arr[1:9:2])

[2 4 6 8]


In [46]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:9:2])


[2 4 6 8]


In [49]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr[0:3,3:])

[[ 4  5]
 [ 9 10]
 [14 15]]


In [58]:
#Advanced Indexing
arr=np.array([[1,2,3,4,5],[7,8,9,10,11]])
ind=[1,4]
print(np.take(arr,ind))
print(np.take(arr,ind,1))



[2 5]
[[ 2  5]
 [ 8 11]]


In [4]:
#Iterating using nditer() function
arr=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(arr):
    print(x)
for x,ind in np.ndenumerate(arr):
    print(ind,x)

1
2
3
4
5
6
1 (0, 0)
2 (0, 1)
3 (0, 2)
4 (1, 0)
5 (1, 1)
6 (1, 2)


In [5]:
arr1=arr[1:3].copy()
print(arr1)

[[4 5 6]]


In [6]:
#transpose and swapaxes
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.T)
print(np.swapaxes(arr,0,1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [10]:
#Joining and splitting of array
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
print(np.hsplit(arr1,3))
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))




[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [11]:
#Aggregate functions in numpy
arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.corrcoef(arr))


21
1
6
3.5
3.5
1.707825127659933
2.9166666666666665
[[1. 1.]
 [1. 1.]]


In [16]:
#Comulative functions in numpy
arr=np.array([[1,2,3],[4,5,6]])
print(np.cumsum(arr))
print(np.cumprod(arr))



[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]


In [17]:
#usages of where in numpy
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.where(arr%2==0,"even","odd"))
print(np.where(arr>5,"greater than 5","less than or equal to 5"))


['odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd']
['less than or equal to 5' 'less than or equal to 5'
 'less than or equal to 5' 'less than or equal to 5'
 'less than or equal to 5' 'greater than 5' 'greater than 5'
 'greater than 5' 'greater than 5']


In [18]:
#usages of argwhere
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.argwhere(arr%2==0))


[[1]
 [3]
 [5]
 [7]]


In [19]:
#Vectorization in numpy
arr=np.array([1,2,3,4,5])
print(arr*2)
print(arr+5)
print(arr**2)
print(np.sqrt(arr))


[ 2  4  6  8 10]
[ 6  7  8  9 10]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
#Dealing with NaN and Inf values and missing data
arr=np.array([1,2,np.nan,4,5,np.inf])
print(arr)
print(np.isnan(arr))
print(np.isinf(arr))
print(np.nansum(arr))



[ 1.  2. nan  4.  5. inf]
[False False  True False False False]
[False False False False False  True]
inf
